#!/usr/bin/python
import sys
import commands
call = "/home/cristiano/Downloads/arduino-1.0.5/hardware/tools/avrdude2  -b 9600 "
for i in range(1,len(sys.argv)):
	call+= sys.argv[i] + " "
print(call)
print(commands.getoutput(call))
